version: 2
registries:
  npm-mirror:
    type: npm-registry
    url: https://registry.npmmirror.org
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-mirror
    schedule:
      interval: "weekly"
