language: node_js
service: docker
sudo: required
env:
  - KAFKA_HOST=localhost:9092
before_script:
  - ./run_docker.sh

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"