language: node_js
service: docker
sudo: required
env:
  - LOGSTASH_HOST=localhost
  - LOGSTASH_PORT=12000
before_install:
  - mkdir -p  ~/settings/
  - cp ci/logstash.conf ~/settings/
  - docker run --rm -it -v ~/settings/:/usr/share/logstash/config/ docker.elastic.co/logstash/logstash:7.1.1

node_js:
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"